### ISSUE TITLE
Solve license confusion

### ISSUE THREAD

**Issue by beothorn** [junrar/junrar#10]
There are different, mutually excluding licenses on some files GPL (/junrar/src/main/java/com/github/junrar/Volume.java).
Not sure how to solve this.

**Comment by beothorn** [comment]
@Rogiel I see that you've added the GPL license, but the license refeers to a project seedbox . Was that your intent?

**Comment by Rogiel** [comment]
@beothorn The GPL headers are probably a mistake from another project I was working on. Since the code is mine, you are free to use it however you want and change its license to whatever you see fit.

**Comment by beothorn** [comment]
Thanks a lot @Rogiel :)
I'll remove the headers for the next deploy
