### ISSUE TITLE
Get a specific inputstream from a rar containing multiple items.

### ISSUE THREAD

**Issue by NanyangTaiji** [junrar/junrar#103]
From List<ContentDescription> contentDescriptions = Junrar.getContentsDescription(testDocuments),   can I get an input stream for a specific contentDescription?

**Comment by gotson** [comment]
You can't get it from a `ContentDescription`, but you can get it from a `FileHeader` via `Archive#getInputStream(FileHeader hd)`.

You can loop through file headers from an `Archive` via `Archive#getFileHeaders()` or by iterating as `Archive` implements `Iterable<FileHeader>`.
