### ISSUE TITLE
Error unpacking large file(>2G)

### ISSUE THREAD

**Issue by xiaokanmengsi** [junrar/junrar#104]
**Describe the bug**
Error unpacking large file(>2G).

**To Reproduce**
When unpacking a large file(>2G),The program will report an error.

**Expected behavior**
I want to be able to unzip large files.

**File**
If possible, please attach or provide a link to the RAR file.
On line 124 of RandomAccessInputStream.readUntil() function ,the 'length'  variable is int, wen the file length is large then Integer.MAX_VALUE, the 'length' variable whill be negative, then the program will not read the content.
**Environment (please complete the following information):**
 - OS: [Windows]
 - Junrar version: [7.5.3]

**Additional context**
Function RandomAccessInputStream.readUntil() put what you read in a vector, when the file is too large may happen OOM.

**Comment by gotson** [comment]
Can you provide the stack trace?

**Comment by gotson** [comment]
Can you provide sample code on how you use the library in that case? Are you using a stream or a file?

**Comment by xiaokanmengsi** [comment]
> Can you provide sample code on how you use the library in that case? Are you using a stream or a file?

`import com.github.junrar.Archive;
import com.github.junrar.rarfile.FileHeader;

import java.io.FileInputStream;
import java.io.FileOutputStream;

/**
 * @author chengpei
 */
public class RarUtil {

    public static void main(String[] args){
        String rarPath = "D:\\test\\source.rar";
        String destinationPath = "D:\\test\\unrar\\";
        try {
            unrar(rarPath,destinationPath);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * unrar
     * @param rarPath rar file path
     * @param destinationPath unrar file path
     */
    public static void unrar(String rarPath, String destinationPath) throws Exception{
        try (FileInputStream inputStream = new FileInputStream(rarPath);
             final Archive archive = new Archive(inputStream);
             FileOutputStream outputStream = new FileOutputStream(destinationPath)){
            while (true) {
                FileHeader fileHeader = archive.nextFileHeader();
                if (fileHeader == null) {
                    break;
                }
                archive.extractFile(fileHeader, outputStream);
            }
        } catch (Exception e){
            throw e;
        }
    }
}`


This is the stack trace:
com.github.junrar.exception.CorruptHeaderException
	at com.github.junrar.Archive.readHeaders(Archive.java:345)
	at com.github.junrar.Archive.setChannel(Archive.java:199)
	at com.github.junrar.Archive.setVolume(Archive.java:811)
	at com.github.junrar.Archive.<init>(Archive.java:149)
	at com.github.junrar.Archive.<init>(Archive.java:178)
	at com.vrv.vap.generator.util.RarUtil.unrar(RarUtil.java:35)
	at com.vrv.vap.generator.util.RarUtil.main(RarUtil.java:21)

**Comment by gotson** [comment]
A recommendation, if you have a file on disk, it's better to use the methods that take a `File` instead of an `InputStream`, this will be more performant

**Comment by xiaokanmengsi** [comment]
> A recommendation, if you have a file on disk, it's better to use the methods that take a `File` instead of an `InputStream`, this will be more performant

改用文件之后可以正常解压，但是用FileInputStream的时候会报错，报错的方法是RandomAccessInputStream.readUntil的124行，当文件长度大于int的最大值时，变量length会变成负数。

**Comment by gotson** [comment]
I can't read Chinese, but i roughly get what you said using Google Translate.

When using a `File`, junrar uses `RandomAccessFile` which is part of JDK. There is no such thing for streams, so we have our own implementation of `RandomAccessInputStream` which does caching in memory. It's less efficient to do caching in memory than to use the `RandomAccessFile`.

**Comment by xiaokanmengsi** [comment]
> I can't read Chinese, but i roughly get what you said using Google Translate.
> 
> When using a `File`, junrar uses `RandomAccessFile` which is part of JDK. There is no such thing for streams, so we have our own implementation of `RandomAccessInputStream` which does caching in memory. It's less efficient to do caching in memory than to use the `RandomAccessFile`.

When using FileInputStrean, RandomAccessInputStream will be wrong every time, you can debug it use my code, when the 'length' is reach Integer.MAX_VALUE, then the 'length' will be negative,so the thread can not read anything.

**Comment by gotson** [comment]
i fixed it, thanks for your analysis. But use `File` instead of `InputStream` if you can, you will have better perf.

**Comment by xiaokanmengsi** [comment]
I hope you can fix this in the BUG in next version as soon as possible. Thank you very much!
