### ISSUE TITLE
[BUG] Special characters are not recognized anymore

### ISSUE THREAD

**Issue by AlexisJehan** [junrar/junrar#108]
**Describe the bug**
Special characters in filenames are not recognized anymore. It was fixed in https://github.com/junrar/junrar/issues/34 but the problem is present again in last versions.

**To Reproduce**
```java
final var file = Path.of("issue.rar");
Junrar.getContentsDescription(file.toFile()).forEach(System.out::println);
```
```
Exception in thread "main" com.github.junrar.exception.CorruptHeaderException: Invalid filename: ?.txt
	at com.github.junrar.rarfile.FileHeader.<init>(FileHeader.java:170)
	at com.github.junrar.Archive.readHeaders(Archive.java:450)
	at com.github.junrar.Archive.setChannel(Archive.java:199)
	at com.github.junrar.Archive.setVolume(Archive.java:811)
	at com.github.junrar.Archive.<init>(Archive.java:149)
	at com.github.junrar.Archive.<init>(Archive.java:170)
	at com.github.junrar.Junrar.createArchiveOrThrowException(Junrar.java:121)
	at com.github.junrar.Junrar.getContentsDescription(Junrar.java:76)
```

**Expected behavior**
Should print `テ.txt`.

**File**
[issue.zip](https://github.com/junrar/junrar/files/9961344/issue.zip) (extract to get the RAR file)

**Environment**
 - OS: Windows
 - Junrar version: 7.5.4 (latest)

**Comment by gotson** [comment]
It's covered by tests though https://github.com/junrar/junrar/blob/a26a8d251ed0d3cbaa9acc5289be184a38b84415/src/test/java/com/github/junrar/ArchiveTest.java#L388

**Comment by AlexisJehan** [comment]
It works with the `unicode.rar` file, effectively:
```
ウニコド.txt: 67
新建文本文档.txt: 10
```

Maybe the file I created is encoded differently? I made it with Winrar on Windows checking the RAR4 format.

**Comment by gotson** [comment]
I cannot reproduce on my macbook, it works fine. Could it be something with how your Java is configured?

**Comment by gotson** [comment]
Would you be able to produce a minimum reproducible repo on Github, showing that it works with a previous version and fails with 7.5.4?

**Comment by AlexisJehan** [comment]
I'm using Windows 10 64 bits and Adoptium JDK 11.0.16.1+1 (I also tried Adoptium JDK 18.0.2.1+1).

Here is the reproductible repo, with my outputs in the README file: https://github.com/AlexisJehan/JunrarIssue108
(The issue appears since Junrar 7.5.3)

**Comment by gotson** [comment]
Thanks, I have a fair idea where the big could be, but I want to perform a repro first.
