### ISSUE TITLE
Is it possible to extract archive from InputStream, for example?

### ISSUE THREAD

**Issue by sshikov** [junrar/junrar#11]
I have a .rar archive in Hadoop hdfs file system. There is no such thing as java.io.File there.

**Comment by beothorn** [comment]
Does this help?
```java
final InputStream resourceAsStream = Foo.class.getResourceAsStream("foo.rar");//only for a single rar file
Junrar.extract(resourceAsStream, tempFolder);
```

**Comment by sshikov** [comment]
Let me try. Looks like a solution, thanks.

**Comment by beothorn** [comment]
Cool. I'll close this issue, if this is not enough please open another one with more details of what you need.
