### ISSUE TITLE
FileHeader times change depending on the current timezone

### ISSUE THREAD

**Issue by gotson** [junrar/junrar#111]
Hi @andrebrait ,

i feel like #76 introduced a bug around `FileHeader` times.

I'm running `ArchiveTest.ExtendedTimeTest` and i get different `mtime` depending on the default timezone:

```
Timezone: Asia/Kolkata
mtime as Date: Wed Feb 23 10:24:19 IST 2022
mtime as FileTime: 2022-02-23T04:54:19.1915433Z

Timezone: America/Los_Angeles
mtime as Date: Wed Feb 23 10:24:19 PST 2022
mtime as FileTime: 2022-02-23T18:24:19.1915433Z

Timezone: Europe/Amsterdam
mtime as Date: Wed Feb 23 10:24:19 CET 2022
mtime as FileTime: 2022-02-23T09:24:19.1915433Z

Timezone: America/Sao_Paulo
mtime as Date: Wed Feb 23 10:24:19 BRT 2022
mtime as FileTime: 2022-02-23T13:24:19.1915433Z
```

Here is what `rar` command line gives me for that file:

```
        Name: files/test/short-text.txt
        Type: File
        Size: 22
 Packed size: 22
       Ratio: 100%
       mtime: 2022-02-23 10:24:19,191543300
       ctime: 2022-02-23 10:34:59,759754700
       atime: 2022-03-02 18:45:18,694091100
  Attributes: ..A....
       CRC32: 8A3BE83B
     Host OS: Windows
 Compression: RAR 1.5(v29) -m0 -md=128K
```

However in the test comment i see:

```
Original timestamps:
MTime: 2022-02-23T09:24:19.191543300Z
CTime: 2022-02-23T09:34:59.759754700Z
ATime: 2022-03-02T17:45:18.694091100Z
```

which is different from what the `rar` CLI gives me.

`FileTime` doesn't have a timezone AFAIK, and thus should be timezone insensitive.

What do you reckon?

**Comment by andrebrait** [comment]
DOS times are dependent on timezones.

A DOS time is a packed 16-bit value containing Year (since 1980), Month (1 to 12), Day (1 to 31), hour (0 to 23), minute (0 to 59) and seconds (0 to 58, only even seconds gets stored). 

All times in a RAR file are stored as DOS dates. They're therefore timezone dependant, when you're converting them to standard, fixed reference time (like Java's milliseconds since epoch).

See https://codedread.github.io/bitjs/docs/unrar.html#ext-time-structure for more details.

**Comment by andrebrait** [comment]
Additional explanation: RAR has a flag to compensate for the missing odd seconds and it also stores sub-seconds time, but it's still a DOS date, although expanded.

**Comment by andrebrait** [comment]
The test class with multiple timezones is intentional for testing the constancy of the decoded time under different zones 😉

**Comment by gotson** [comment]
so that means we can't convert the times to `Instant` and expect them to match if the timezone doesn't, correct?

So it might not be a bug, but in that case do you have any idea on what's the best way to compare those dates, when they are being compared across timezones ?

I've got a regression test corpus that store JSON files of all the files in the corpus, and i can check the archive process again against the stored value, however when trying to set it up in Github Actions it fails because the dates are offset by 8.

**Comment by gotson** [comment]
Or maybe what i need to do is generate the reference data in UTC, and always compare in UTC?

**Comment by andrebrait** [comment]
No, we can't expect them to match.

If we know the _original_ timezone, though, we can compare it tonthe expected instant at that timezone, maybe using a `LocalDateTime` or something.

But just an FYI, that was already the case before #76. `mTime` was always stored as a DOS date. #76 only added the odd second and sub-seconds parts of it.

It's working as per the specification. We need to change how we compare it in the failing test.

I'd need to take a look at the specific test and see how it's doing it.

**Comment by andrebrait** [comment]
Yes, that would work :) 

If you want to be thorough, you can generate two JSONs, each on a different time zone, and code two tests with two different time zones :) I think I've done something similar in a test already

**Comment by gotson** [comment]
It's working now 😃
