### ISSUE TITLE
FileTime.fromMillis(getDateDos(fileTime)) is not working below android API 26

### ISSUE THREAD

**Issue by saif198** [junrar/junrar#112]
exception:
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/FileTime; 
at com.github.junrar.rarfile.FileHeader.<init>(FileHeader.java:203)

solution:
the java.time package was added only in API 26.
[https://developer.android.com/reference/java/time/package-summary](url)
And for prior versions, you can use org.joda.time.LocalDate

**Comment by gotson** [comment]
This is a Java library that requires Java 8. You can use the Java 6 compatible version (v4.0.0).
