### ISSUE TITLE
Look for useful changes on other forks

### ISSUE THREAD

**Issue by beothorn** [junrar/junrar#15]
Because the main project is unmaintained there is a lot of fragmentation.
Lots of forks with different improvements https://github.com/edmund-wagner/junrar/network/members
It would be nice to scan them and reproduce improvements on this fork.

**Comment by beothorn** [comment]
Some interesting changes

https://github.com/geometer/junrar/commit/c44496d6c64fc09951ccc390374b8517f01ebd9b

https://github.com/awaters1/junrar/commit/28be41d24a7077937f5ef11905c840ed36e3dbe2

https://github.com/NitroXenon/JUnRAR

https://github.com/Cheetozz/junrar

https://github.com/sseide/junrar/commit/5ccda759d68a8f5c489fb20e1a7bfa49f66d82f7

https://github.com/vaemendis/junrar/commit/28663a44434caa900cb584436a120ea7e163a5d8

https://github.com/koroshiya/junrar/commit/06bdd47f56fea1de8fb41c2c3400c4be403ba647

https://github.com/phax/junrar/commits/master

https://github.com/vsubhash/junrar/commit/9831bedeb0deaa1fc82ff13901a5ece7f30beb3b

https://github.com/DarkSupremo/junrar/commits/master

https://github.com/RDamman/junrar/commits/master

**Comment by sethchhim** [comment]
`geometer/junrar@c44496d`

This commit is extremely more performant on Android. PipedInputStream just doesn't work that well for us.

**Comment by rednoah** [comment]
Adding `META-INF/vfs-providers.xml` to the JAR would be nice as well, so `vfs2` can find the RAR plugin, since `vfs2` support is implemented already:
```
<providers>
	<provider class-name="com.github.junrar.vfs2.provider.rar.RARFileProvider">
		<scheme name="rar" />
	</provider>
	<extension-map extension="rar" scheme="rar" />
	<mime-type-map mime-type="application/rar" scheme="rar" />
</providers>
```

**Comment by gotson** [comment]
> Adding `META-INF/vfs-providers.xml` to the JAR would be nice as well, so `vfs2` can find the RAR plugin, since `vfs2` support is implemented already:
> 
> ```
> <providers>
> 	<provider class-name="com.github.junrar.vfs2.provider.rar.RARFileProvider">
> 		<scheme name="rar" />
> 	</provider>
> 	<extension-map extension="rar" scheme="rar" />
> 	<mime-type-map mime-type="application/rar" scheme="rar" />
> </providers>
> ```

@rednoah Would you be able to provide some context on this ? I don't really know VFS nor what it brings. I was thinking of removing it, but if it's useful we can keep it?

**Comment by theobisproject** [comment]
@gotson Th

> 
> 
> > Adding `META-INF/vfs-providers.xml` to the JAR would be nice as well, so `vfs2` can find the RAR plugin, since `vfs2` support is implemented already:
> > ```
> > <providers>
> > 	<provider class-name="com.github.junrar.vfs2.provider.rar.RARFileProvider">
> > 		<scheme name="rar" />
> > 	</provider>
> > 	<extension-map extension="rar" scheme="rar" />
> > 	<mime-type-map mime-type="application/rar" scheme="rar" />
> > </providers>
> > ```
> 
> @rednoah Would you be able to provide some context on this ? I don't really know VFS nor what it brings. I was thinking of removing it, but if it's useful we can keep it?

@gotson This was already added by @beothorn (see the linked commit above his comment)

**Comment by gotson** [comment]
> > > Adding `META-INF/vfs-providers.xml` to the JAR would be nice as well, so `vfs2` can find the RAR plugin, since `vfs2` support is implemented already:
> > > ```
> > > <providers>
> > > 	<provider class-name="com.github.junrar.vfs2.provider.rar.RARFileProvider">
> > > 		<scheme name="rar" />
> > > 	</provider>
> > > 	<extension-map extension="rar" scheme="rar" />
> > > 	<mime-type-map mime-type="application/rar" scheme="rar" />
> > > </providers>
> > > ```
> > 
> > 
> > @rednoah Would you be able to provide some context on this ? I don't really know VFS nor what it brings. I was thinking of removing it, but if it's useful we can keep it?
> 
> @gotson This was already added by @beothorn (see the linked commit above his comment)

I know, i'm wondering what's the use and if we should keep it or remove it.

**Comment by beothorn** [comment]
> > Adding `META-INF/vfs-providers.xml` to the JAR would be nice as well, so `vfs2` can find the RAR plugin, since `vfs2` support is implemented already:
> > ```
> > <providers>
> > 	<provider class-name="com.github.junrar.vfs2.provider.rar.RARFileProvider">
> > 		<scheme name="rar" />
> > 	</provider>
> > 	<extension-map extension="rar" scheme="rar" />
> > 	<mime-type-map mime-type="application/rar" scheme="rar" />
> > </providers>
> > ```
> 
> @rednoah Would you be able to provide some context on this ? I don't really know VFS nor what it brings. I was thinking of removing it, but if it's useful we can keep it?

Someone a long time ago wanted to use junrar from inside a hadoop cluster. I don't think that this is a common usage and there are probably other ways to work around this without vfs.

**Comment by gotson** [comment]
https://github.com/vsubhash/junrar/commit/9831bedeb0deaa1fc82ff13901a5ece7f30beb3b is breaking tests. Some of our test files do have windows separators, and extract fine on Mac and Linux, so this is probably not needed.

**Comment by gotson** [comment]
It seems there is some interesting change [here](https://github.com/RDamman/junrar/commit/94607b0dc34889c1e8ccf943895b87a5f73bb086) about PPM error handling, but i have no idea if those changes make sense or not.

Files concerned:
- Unpack.java
- Decode.java
- ModelPPM.java

**Comment by gotson** [comment]
Some more changes that are difficult to assess: https://github.com/phax/junrar/commit/2b0dc092efdfe522c8dd356af20c444d4e1020a2

**Comment by gotson** [comment]
And this one too: https://github.com/vaemendis/junrar/commit/28663a44434caa900cb584436a120ea7e163a5d8

**Comment by gotson** [comment]
I finished combing the changes listed above. I found only 3 that i cannot really assess (the 3 comments directly above this one).

@sunny-shu if you are up to the challenge, you can have a look at the 3 changes and see if they make sense, and if yes we can port them to our version.
