### ISSUE TITLE
com.github.junrar.exception.RarException: badRarArchive

### ISSUE THREAD

**Issue by lovejing0306** [junrar/junrar#27]
请问这个问题怎么解决！

**Comment by beothorn** [comment]
Does any software with rar support (7zip for example) is able to decompress your file?

Looking at the code it may be possible that your rar is invalid or has a version that is not supported.

**Comment by gotson** [comment]
@lovejing0306 i am closing this since the issue is quite old. Please reopen if you still have the issue, and provide the file if possible so we can have a look.
