### ISSUE TITLE
Support for Chinese characters

### ISSUE THREAD

**Issue by zzustu** [junrar/junrar#34]
https://github.com/junrar/junrar/blob/ae7bd9bb0590a530ff8b2057e1a0c403c004085c/src/main/java/com/github/junrar/Junrar.java#L159

使用`fileHeader.getFileNameString()`获取FileName中文会乱码，而使用
`fileHeader.getFileNameW()`
就不乱码

**Comment by 361442342** [comment]
i have reproduced the problem,and found why does it happen.  i will submit a PR to fix it soon.

**Comment by 361442342** [comment]
@beothorn 
`            if (isUnicode()) {
                int length = 0;
                fileName = "";
                fileNameW = "";
                while (length < fileNameBytes.length
                        && fileNameBytes[length] != 0) {
                    length++;
                }
                byte[] name = new byte[length];
                System.arraycopy(fileNameBytes, 0, name, 0, name.length);
                fileName = new String(name);
                if (length != nameSize) {
                    length++;
                    fileNameW = FileNameDecoder.decode(fileNameBytes, length);
                }
            } else {
                fileName = new String(fileNameBytes);
                fileNameW = "";
            }`
I know when LHD_UNICODE is set.the filename consist of local coding name and unicode coding name.
in your code what charset you used to decode for "FileNameDecoder.decode(fileNameBytes, length);"

**Comment by gotson** [comment]
@sunny-shu beothorn is not maintaining the project, i am taking over. I am happy to have a look at your PR, we can also add a test file in the test scenarios to make sure it works fine.
