### ISSUE TITLE
Multi part file not support well

### ISSUE THREAD

**Issue by maocoj** [junrar/junrar#35]
When decopressing multi part file,   if the last file in xxx.part1.rar has no data in next volume, there will not go on decompressing xxx.part2.rar

**Comment by 361442342** [comment]
maybe your file name does not meet the specification.
you can upload your file,i will try to figure it out.

**Comment by sunny-shu** [comment]
@maocoj 
i read the rar format,i found that if you split your archive into multi part.the count has not been recorded in the file.
so  if the last file in xxx.part1.rar has no data in next volume, there will not go on decompressing xxx.part2.rar。
i will fix this bug,can you upload your file for me to test my code.
