### ISSUE TITLE
NPE on a possibly corrupt rar file 

### ISSUE THREAD

**Issue by sparkhi** [junrar/junrar#36]
Hello,

I came across a NullPointerException from the `Archive` class which I wanted to bring to your notice. I believe this is happening on a corrupt file or an unsupported version (not really sure)

The problem happens on the file when reading headers, `BaseBlock.getHeaderType()`  one of the Bytes that it comes across is a 0, hence it returns a `null`.  

In the `Archive` class, there is a `switch` case based on the return value from above in the method `readHeaders`. The switch case throws a `NullPointerException`, I think handling the NPE and returning a RarException would be a better thing to do from here. 

I'm attaching a file which can reproduce the issue. The rar in question is inside the zip.

[some-corrupt-file.zip](https://github.com/junrar/junrar/files/4494089/some-corrupt-file.zip)

Thanks,

**Comment by 361442342** [comment]
your file format is broken up. you can use winrar to test it.

**Comment by gotson** [comment]
Indeed the file is corrupt:

```
rar t some-corrupt-file.rar                                                                                                                                  Thu Jul 16 10:27:00 2020

RAR 5.91   Copyright (c) 1993-2020 Alexander Roshal   25 Jun 2020
Trial version             Type 'rar -?' for help

Corrupt header is found
Main archive header is corrupt

Testing archive some-corrupt-file.rar

Corrupt header is found
No files to extract
```

It would make sense indeed to handle this and throw a `RarException` instead of a NPE. I'll see if I can add this.

**Comment by sunny-shu** [comment]
@gotson 
hi gotson ,i've found the problematic code,please merge my prior PR soon. so i can create new PR for this

**Comment by gotson** [comment]
> @gotson
> hi gotson ,i've found the problematic code,please merge my prior PR soon. so i can create new PR for this

Thanks. Can you maybe add a test with the provided file in the PR as well as the code fix?

**Comment by sunny-shu** [comment]
ok,I use sparkhi‘s data as test data, is that ok?

**Comment by gotson** [comment]
> ok,I use sparkhi‘s data as test data, is that ok?

yes!
