### ISSUE TITLE
New maintainer for this project

### ISSUE THREAD

**Issue by beothorn** [junrar/junrar#38]
There is no one actively maintaining this project.
If anyone who **is using this library** in an **active project** have interest in taking over let me know.

**Comment by 361442342** [comment]
hello,recently i focus on zip，tar,zip。 i want to make a contribution. 
so i can take this job. except the issue, is there any other things i can do?

**Comment by gotson** [comment]
Hi, I use this library as part of https://github.com/gotson/komga

I have no skills regarding the low level work that this library is doing, but I can definitely handle managing the github, grooming the issues, and setting up automatic builds and publish packages on maven central.

**Comment by gotson** [comment]
Thanks @beothorn for giving me the rights on the organisation. I will try to organise the repo and issues in the coming weeks.
