### ISSUE TITLE
Different results when initialising Archive with InputStream vs FileVolumeManager

### ISSUE THREAD

**Issue by xavier630** [junrar/junrar#39]
In my case, making an Archive with 1. and then iterating through the files finds N number of files, but using 2. and iterating through finds 4N files.

1.
```
InputStream inputStream = new FileInputStream(file);
final Archive archive = new Archive(inputStream);
```
2.
```
final Archive a = new Archive(new FileVolumeManager(file));
```

The iteration is along the lines of:
```
   while (true) {
                FileHeader fh = a.nextFileHeader();
                if (fh == null) {
                    break;
                }

                String path = fh.getFileNameString();
                if (path.toLowerCase().contains("some_text")) {
                    try {
                        // Do something
                    } catch (IOException e) {
                        // Do something else
                    }
                }
            }
```

It's plausible that when using a InputStream, the next file header from the archive ends up being null one sooner than it should be.

**Comment by 361442342** [comment]
maybe your file name does not meet the specification.
you can upload your file,i will try to figure it out.

**Comment by 361442342** [comment]
can you  upload your file,i will try to figure it out.

**Comment by 361442342** [comment]
@xavier630 
i use winrar to create a Archive and test it with your code, and the problem does not come up.
uploading your file may be helpful.

**Comment by xavier630** [comment]
Unfortunately I can't upload the exact files since they are work-related but perhaps it's worth noting as well that they were many GBs large

**Comment by gotson** [comment]
Are the files multi volume?

Can you also check the files via the official unrar command line tools and post results?

**Comment by gotson** [comment]
And one more question, what's the correct number of files you expect? Is 1 or 2 correct?

**Comment by xavier630** [comment]
Apologies - this happened about half a year ago and I've since switched projects. If I get access to the files again I'll see if I can answer those questions.

Feel free to close since no one else can reproduce it.
