### ISSUE TITLE
how can i unrar with password

### ISSUE THREAD

**Issue by xiamaoxuan** [junrar/junrar#40]
how can i unrar with password

**Comment by 361442342** [comment]
@beothorn 
i read the code,it is not supported yet, am i right?

**Comment by beothorn** [comment]
Yes, not supported. Looking at the code we just print
"archive is encrypted cannot extract"
and exit

**Comment by sunny-shu** [comment]
@gotson  @beothorn 
i plan to work on this issue this week, i will do it based on the source code of winrar. Is there anything i need to pay attention to

**Comment by gotson** [comment]
It seems someone already did it in one of the fork, check here https://github.com/koroshiya/junrar/commit/06bdd47f56fea1de8fb41c2c3400c4be403ba647

Maybe you can port the changes.

**Comment by sunny-shu** [comment]
i am working on it.  koroshiya/junrar is not based on the latest code,so It may take a few days to resolve this matter

**Comment by gotson** [comment]
> i am working on it. koroshiya/junrar is not based on the latest code,so It may take a few days to resolve this matter。
> 
> the feature is a fake,I found that his code was not executed.it is amazing that it can still run normally。
> I'm still analyzing his code，when the feature is ready,i will push a PR.

I didn't test his fork yet, but i noticed it was using [gnu crypto](https://www.gnu.org/software/gnu-crypto/) for the Rijndael algorithm (which is not implemented in our version). The jar is added directly in the project, which is bad practice. It seems the jar is available on [Maven Central](https://search.maven.org/artifact/org.gnu/gnu-crypto/2.0.1/jar), but the project seems abandoned since 2014.

A good replacement could be [Bouncy Castle](https://www.bouncycastle.org/java.html), which is a well-known crypto library for Java.

**Comment by gotson** [comment]
> the feature is a fake,I found that his code was not executed

I don't agree, i have tested it, and i found it it can:
- list content of encrypted files, which is not possible in our version because the file listing is encrypted
- extract password protected files

However, i couldn't extract files from an encrypted archive, i get a CRC error.

**Comment by sunny-shu** [comment]
hi gotson，I found the key point in  koroshiya/junrar.now i unpack the encrypted successfully.
Next, I will replace gnu crypto  according to your opinion and add the test case。
After all problems are solved, I will raise PR。
thank you for your advice.

**Comment by sunny-shu** [comment]
hi gotson，the api of Rijndael is different from the JDK.
I tried many times with jdk's api，It cannot decrypt correctly。
I integrated the original author's code，You do the rectification for Rijndael. is that ok?

**Comment by gotson** [comment]
You can make a PR, I'll have a look, thanks!
