### ISSUE TITLE
review class organizations and public API

### ISSUE THREAD

**Issue by gotson** [junrar/junrar#49]
I spent quite some time understanding the current organization of the code, here is what i have gathered so far:
- To me there are 2 possible entry points in the library:
  - the `Junrar` class which provides only `static` methods. Those methods can be considered as helper methods, and remove the need to instantiate the `Archive` class.
  - the `Archive` class, which provide more fine-grained operations, for example to get access to the `FileHeader`s directly, or to use the `UnrarCallback` to monitor progress, or to have more details on the archive's option, like encryption, solid, etc.

On the other side, there are 2 interfaces `Volume` and `VolumeManager` that helps (via their implementation for `File` and `InputStream`) to handle RAR archives spanning multiple files.

One problem i have is that some of the `Junrar` methods and `Archive` constructors accept a `VolumeManager` as argument, de-facto exposing this interface in the public API, which means the implementation are also leaking in the client.

Given that both `FileVolumeManager` and `InputStreamVolumeManager` are just wrappers around `File` and `InputStream`, those should not be exposed in the public API, which should instead take the native `File` (or `String` as path) and `InputStream` arguments.

It seems most if not all classes are `public` at the moment. The underlying implementation should be made private as much as possible.

**Comment by gotson** [comment]
@sunny-shu i have created a branch that simplifies the IO, but it will have an impact on your current PR for decryption.

I would like to get your view, can you check https://github.com/junrar/junrar/tree/io-simplification ?

**Comment by sunny-shu** [comment]
> @sunny-shu i have created a branch that simplifies the IO, but it will have an impact on your current PR for decryption.
> 
> I would like to get your view, can you check https://github.com/junrar/junrar/tree/io-simplification ?

ok,i will take check today. 
The api is indeed a bit confusing。Some files in the io directory are not used，I guess the original author also wanted to refactor the code。

**Comment by gotson** [comment]
i have updated `dev` branch with some more refactoring, cleaning up the public API for `Archive` and `Junrar`. `VolumeManager` is not exposed anymore to consumers in both those classes.

I have noticed that there is some use of the `assert` keyword in the code, but without the special flag `-ea` those are never triggered. I will check how to replace them with proper checks.

**Comment by gotson** [comment]
> I have noticed that there is some use of the `assert` keyword in the code, but without the special flag `-ea` those are never triggered. I will check how to replace them with proper checks.

There's only 5 of those, and they are not actually used to check parameters, so we can leave those.

I have further cleaned up the Volume classes, regrouped them in the `volume` package.

**Comment by gotson** [comment]
I think I'm done with the cleanup, should be good to merge to master.

@sunny-shu cam you have a quick look before I merge?

**Comment by sunny-shu** [comment]
i have reviewed your code.
Beautiful work！
