### ISSUE TITLE
[QUESTION / Architecture] DocumentFile support for Android

### ISSUE THREAD

**Issue by RobbWatershed** [junrar/junrar#56]
I'm about to fork and use this library on an Android 10 project where all file I/O has been rewritten to use `DocumentFile` instead of plain Java `File`. We did that in order to work with the Android SAF and comply to scoped storage security constraints.

Thing is, I do know how to change the code to replace `File` with `DocumentFile` but I have no idea how to properly integrate these changes into the library's structure without introducing Android dependencies that would certainly break stuff for "pure Java" users.

I'd like to ask to those who are familiar with this lib (and with Gradle) what would be the cleanest way to do that. Is there some new module / structure we could set up in Gradle ?

**Comment by gotson** [comment]
Problem is see is that DocumentFile does not guarantee there's a File behind. I don't know much Android SDK, but I doubt it would be as simple as replacing one with the other.

**Comment by gotson** [comment]
I've found this https://stackoverflow.com/questions/39577708/is-it-possible-to-get-a-regular-file-from-documentfile and also this https://stackoverflow.com/questions/43026027/reading-zipfile-with-android-documentfile

You could probably use the library as is by using streams.

**Comment by RobbWatershed** [comment]
> Problem is see is that DocumentFile does not guarantee there's a File behind. I don't know much Android SDK, but I doubt it would be as simple as replacing one with the other.

That's for sure !  I said I knew how to do it; I didn't say it would be easy.


> You could probably use the library as is by using streams.

That would definitely be the best solution. `extract` can already work with streams. However `getContentsDescription` does not. Adding another method variant that takes a stream as an input would probably be faster/easier than replacing `File`

I'll keep you informed. Worst case, the 2nd SO link suggests to reconstitute the file's absolute path to feed it back to `File`, which is an okay workaround.
