### ISSUE TITLE
[Optimization] Junrar shouldn't load the entirety of the file into memory

### ISSUE THREAD

**Issue by RobbWatershed** [junrar/junrar#63]
**Describe the bug**
When initializing an archive to read its headers :

```java
try (InputStream fi = FileHelper.getInputStream(context, file); BufferedInputStream bis = new BufferedInputStream(fi, BUFFER)) {
   Archive input = new Archive(bis);
}
```

Junrar loads the whole RAR file into memory (see screencap below), which isn't shocking in a desktop environment, but causes issues in a mobile environment (Android) where resources are more scarce. Some of my users gets OOM crashes because of that, when trying to read big files.

**Stracktrace after an OOM for a 510MB RAR file**
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 528 byte allocation with 63984 free bytes and 62KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 443285504 bytes)
			   at com.github.junrar.io.RandomAccessInputStream.readUntil(RandomAccessInputStream.java:106)
			   at com.github.junrar.io.RandomAccessInputStream.read(RandomAccessInputStream.java:72)
			   at com.github.junrar.io.RandomAccessInputStream.readFully(RandomAccessInputStream.java:93)
			   at com.github.junrar.io.SeekableReadOnlyInputStream.readFully(SeekableReadOnlyInputStream.java:51)
			   at com.github.junrar.io.RawDataIo.readFully(RawDataIo.java:75)
			   at com.github.junrar.Archive.readHeaders(Archive.java:312)
			   at com.github.junrar.Archive.setChannel(Archive.java:178)
			   at com.github.junrar.Archive.setVolume(Archive.java:675)
			   at com.github.junrar.Archive.<init>(Archive.java:128)
			   at com.github.junrar.Archive.<init>(Archive.java:157)`

**Memory monitor when loading a 285MB RAR file with the code snipped above**
![image](https://user-images.githubusercontent.com/35880555/103868465-37380980-50c9-11eb-8fe6-7e5e4df40b66.png)
NB : loading happens twice because my code calls it twice 😉 

**Expected behavior**
Junrar should only load what's useful in memory (e.g. headers, binary data of files to unrar), not the _entire file_.

**File**
Same on any RAR file

**Environment (please complete the following information):**
 - OS: Android 8.1 to 10 (didn't test on other versions)
 - Junrar version: 7.4.0

**Comment by gotson** [comment]
You could use `File` instead of `InputStream` to reduce memory usage. When using a `File`, it's using `RandomAccessFile`, but when using `InputStream` we use `RandomAccessInputStream`, which is an internal implementation based on the JAI MemoryCacheSeekableStream class, it uses a memory cache to allow seeking within an `InputStream`.

The problem comes from the structure of the rar files, headers are spread across the file, and in order to parse the headers, you need to read the whole file.

**Comment by RobbWatershed** [comment]
Thanks for the quick answer.

> You could use File instead of InputStream to reduce memory usage

Unfortunately I can't use `File` because of technical constraints of the Android platform (need to use SAF / `DocumentFile` since Android 10 to access certain locations such as SD card storage).

> The problem comes from the structure of the rar files, headers are spread across the file, and in order to parse the headers, you need to read the whole file.

I've worked with files structures with similar constraints in the past (MP4 namely). Reading the whole file doesn't mean putting it all into memory. One should be able to seek to key locations within the file by using header information only, which take up <2% of total file size. There's no need to cache the remaining 98% of compressed data to do that.

When the "cache" is just putting the whole file in memory, it's not called a cache anymore...

**Comment by gotson** [comment]
Are you referring to streams that support `mark()`?

**Comment by gotson** [comment]
> I've worked with files structures with similar constraints in the past (MP4 namely). Reading the whole file doesn't mean putting it all into memory. One should be able to seek to key locations within the file by using header information only, which take up <2% of total file size. There's no need to cache the remaining 98% of compressed data to do that.

That's the exact behaviour of Junrar when using a `File`, with the underlying `RandomAccessFile`.

Streams do not support random access, hence the internal implementation.

The issue you have is Android specific, with Google preventing developers to access `File` anymore (if I understand correctly), and it's understandable because the abstraction they provide is necessary, as `DocumentFile` does not necessarily represent a file on disk, but could also a file in a cloud provider for example. So the only way to get the content is via a stream. 

I don't know if those streams support mark and reset. In theory, if they did, you could use another implementation of `SeekableReadOnlyInputStream` that would use mark and reset to offer random access in the underlying stream.

Feel free to send a PR if you manage to get something working.

**Comment by RobbWatershed** [comment]
Your description of the Android state of things is quite accurate, and the possible fix with mark / reset is indeed something that could work.

And yes, the stream implementation I'm using does support these two methods. I'll see what I can do 😄

**Comment by RobbWatershed** [comment]
I've wrapped my head around this issue and came to the following observations :

As it is designed right now, Junrar seems to need random access not for listing but for extracting :
1. It reads headers in a first pass, while constructing `Archive`
2. Then it extracts files in a 2nd pass, using the same stream. `ComprDataIO.init` gives the order to go back to the interesting part of the stream using `SeekableReadOnlyByteChannel.setPosition`, which is the only place in the whole library where the stream cursor can move backwards

Now with the solution : the way `mark` works wouldn't solve anything memory-wise, as the `InputStream`'s own buffer would cache file data as the cursor advances. 

I've come to the conclusion that the only way to acheive what I have in mind would be to rewrite the implementation of the transactional API (e.g. `Junrar.extractContent`) so that Junrar reads headers _and_ extracts while traversing the stream in one single pass.

I'll give it a try and keep you informed.

**Comment by gotson** [comment]
`InputStream` doesn't have a buffer, only `RandomAccessInputStream` does. What i was suggesting is for you to implement the `SeekableReadOnlyByteChannel` interface for an `InputStream` that does support `mark()` and `reset()` (typically for Android). That would look like `SeekableReadOnlyInputStream` but would not use the underlying `RandomAccessInputStream`, but a normal `InputStream` instead. That way you would not use the memory buffer, and would rely on `mark`/`reset` to handle random access.

If the stream is really completely rewindable, it should be easy to emulate a complete random access with `mark` / `reset`. You could use `0` as the reference point, and do all operations from that. For example:
- if you are at position `5`, and need to go to `2`, you `reset` to `0`, `mark(0)` again, and `seek(2)`.
- if you are at position `5`, and need to go to `10`, you `seek(5)`

---

In your initial code i see that you wrap the `InputStream` into a `BufferedInputStream`. `BufferedInputStream` supports `mark`/`reset` all the time. Are you certain that the underlying `InputStream` also supports it?

Also, by doing so you would use 2 buffers, the one from `BufferedInputStream` and the one from Junrar's `RandomAccessInputStream`.

**Comment by RobbWatershed** [comment]
Sorry about this, I went too fast to my conclusions and didn't explain my initial observations :

- I was mistaken when I said the stream provided by `DocumentFile` supports `mark()` and `reset()` - it actually doesn't

- If I were to follow what you have in mind, I would have to call `mark(fileSize)`, let Junrar parse the headers, and call `reset()` when it needs to go back to the beginning of the archive to extract the files. To do that, I have to use a "wrapping" stream solution (such as `BufferedInputStream` or `PushbackInputStream`) on top of the `InputStream` provided by `DocumentFile`, as the latter doesn't support `mark()` and `reset()`. Bad news is both of these solutions make `mark()` and `reset()` possible by storing read content into a buffer that is used to go backwards into the stream when calling `reset()`.

That's why I said the buffer would anyway grow to the whole size of the file.

**Comment by gotson** [comment]
If your InputStream doesn't support mark then I don't think there's any way to handle that better. 

You could write to a temp file, then use the archive from a File, if Android let you do it?

**Comment by RobbWatershed** [comment]
> You could write to a temp file, then use the archive from a File, if Android let you do it?

Yup, that could work, but the point of my issue is to optimize resources. Trading RAM for disk space would just create a different kind of optimization issue that other users would report (the ones with very few remaining disk space... and there are plenty of them !)

**Comment by RobbWatershed** [comment]
Anyway, I'm gonna try my "single pass" idea and submit a PR if that works. If not, I'll close the issue.

**Comment by RobbWatershed** [comment]
I finally found a proper way to decrease memory usage without rewriting half the library.

As you probably knew already, it was way too ambitious and risky to try and rewrite Junrar to make it do a single pass when extracting. I figured that out after reading the code carefully, which I didn't really do last week.

However, by looking at the API from https://github.com/omicronapps/7-Zip-JBinding-4Android, I suddenly realized we could do something else : instead of asking an `InputStream` to build `Archive`, we could ask for a `SeekableReadOnlyByteChannel` and let the user give his own implementation.

As far as my Android issue goes, the trick not to consume too much memory is to re-construct a brand new `InputStream` from the `DocumentFile` everytime the stream needs to seek backwards. That way I can manage not to load everything into memory.

=> Would that sound acceptable to you to create new `Archive` constructors that use `SeekableReadOnlyByteChannel` instead of `InputStream` ?

**Comment by gotson** [comment]
Good that you found out a way!

One thing though, it would need careful understanding on how the DocumentFile behaves when getting an input stream. For instance for a local file that would worl, but if you have a DocumentFile that represents a file in the cloud, like on Google drive or Dropbox, what happens when you get an inputstream everytime?

One way to provide your own implementation is to do like what has been done for vfs, and provide a Volume implementation : https://github.com/junrar/commons-vfs-rar/blob/master/src/main/java/com/github/junrar/vfs2/provider/rar/VFSVolume.java

**Comment by RobbWatershed** [comment]
Closing the issue because it isn't an issue for me anymore. I have eventually chosen to use another library that supports RAR5, among other things. Thanks anyway for your constructive and quick input !

**Comment by gotson** [comment]
> Closing the issue because it isn't an issue for me anymore. I have eventually chosen to use another library that supports RAR5, among other things. Thanks anyway for your constructive and quick input !

May I ask which library you found that supports rar 5?

**Comment by RobbWatershed** [comment]
Sure : https://github.com/omicronapps/7-Zip-JBinding-4Android

I kinda "cheated" as it's a native library with a JNI interface, and not a full Java solution. At first, I intended to take inspiration from it by reviewing code, but I realized the range of supported formats would make it a good candidate for replacement.

**Comment by zzycami** [comment]
I have this problem too. check this https://stackoverflow.com/questions/28897329/documentfile-randomaccessfile
ParcelFileDescriptor can read random. example here: https://github.com/avluis/Hentoid/blob/dcb208eabbfc134b20d68c996cce89989179655e/app/src/main/java/me/devsaki/hentoid/util/ArchiveHelper.java
