### ISSUE TITLE
Remove dependency from org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by Mingun** [junrar/junrar#64]
**Describe the bug**
Not all projects depends on `LoggerFactory`. Such general purpose library should not force to using any library that not strictly necessary for work.

**To Reproduce**
- Create new java project in your favorite IDE
- Add `junrar` dependency only
- Instantiate `Archive` class: `new Archive(new File("file.rar"))`

**Expected behavior**
Object must be created, no exceptions expected

**Environment (please complete the following information):**
 - OS: Any
 - Junrar version: 7.4.0

**Comment by gotson** [comment]
Slf4j is a facade , you can use whatever implementation you want.

**Comment by gotson** [comment]
Also check http://www.slf4j.org/faq.html#optional_dependency

**Comment by gotson** [comment]
You did not describe the symptom, only mentioned reproduction steps. Can you clarify the symptoms you experience?

**Comment by Mingun** [comment]
Thank you for your help! I see you points and find them reasonable. Actually, I see that logging facade is small and it shouldn't cause rejection in those who seek to keep theirs programs as small as possible.

One thing I still think need to be done: mention in readme that you also need to add dependency to the `slf4j-api-<version>.jar`, because otherwise `ClassNotFoundException("org/slf4j/LoggerFactory")` thrown when you try to use `Archive` class

**Comment by gotson** [comment]
It should not be needed. Can you provide a reproduction repo?

**Comment by Mingun** [comment]
Yes, if you use modern build systems, such as maven or gradle that downloads necessary dependency automatically, you will not face with the problem. However I support project which uses old good `ant` and all dependencies is resolving manually.

I attach small `ant` project [issue64.zip](https://github.com/junrar/junrar/files/6136504/issue64.zip) and you can see that it is failed with
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.junrar.Archive.<clinit>(Archive.java:81)
	at ru.mingun.Isssue64.main(Isssue64.java:9)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
/home/mingun/Projects/issue64/nbproject/build-impl.xml:1355: The following error occurred while executing this line:
/home/mingun/Projects/issue64/nbproject/build-impl.xml:961: Java returned: 1
BUILD FAILED (total time: 0 seconds)
```

**Comment by gotson** [comment]
Hmm. Build systems that don't support transitive dependencies.

Well, glad you sorted it out. I don't plan on adding more information on the Readme, people using outdated buidl systems ought to know where to look to find transitive dependencies on the libraries they use.
