### ISSUE TITLE
[BUG] NullPointerException when extracting solid archives

### ISSUE THREAD

**Issue by zhanghai** [junrar/junrar#83]
**Describe the bug**

`Unpack.window` is null during `Archive.extractFile()` if the archive is solid, which results in a `NullPointerException`.

Stacktrace:

```
java.lang.NullPointerException: Attempt to write to null array
     at com.github.junrar.unpack.Unpack.unpack29(Unpack.java:249)
     at com.github.junrar.unpack.Unpack.doUnpack(Unpack.java:116)
     at com.github.junrar.Archive.doExtractFile(Archive.java:587)
     at com.github.junrar.Archive.extractFile(Archive.java:534)
     ...
```

This seems to be a result of `Unpack.init()` only called when `hd.isSolid()` return `false`, and `Unpack.init()` seems to be the only wait to intialize `Unpack.window` which is used unconditionally in `Unpack.unpack29()`.

https://github.com/junrar/junrar/blob/178fd7edd8f243aacb6f7c79e3ea254f7d34d475/src/main/java/com/github/junrar/Archive.java#L682-L684

https://github.com/junrar/junrar/blob/178fd7edd8f243aacb6f7c79e3ea254f7d34d475/src/main/java/com/github/junrar/unpack/Unpack.java#L249

**To Reproduce**

Use junrar to extract a file inside a solid archive, such as https://www.rarlab.com/themes/RARaddin_48x48.theme.rar .

In my case I'm using my own app [Material Files](https://play.google.com/store/apps/details?id=me.zhanghai.android.files) to reproduce but I think any user of this library should encounter the same issue.

**Expected behavior**

Solid archives should be extractable and shouldn't cause a `NullPointerException`.

**File**

https://www.rarlab.com/themes/RARaddin_48x48.theme.rar

**Environment (please complete the following information):**

 - OS: Android
 - Junrar version: 7.4.1

**Additional context**

https://github.com/zhanghai/MaterialFiles/issues/247

**Comment by gotson** [comment]
> Use junrar to extract a file inside a solid archive, such as https://www.rarlab.com/themes/RARaddin_48x48.theme.rar .

You need to extract all the files in sequence for solid archives. Have a look [here](https://github.com/junrar/junrar/blob/d5cc784c937f461be1e71a7a92b4018af8aef8c7/src/test/java/com/github/junrar/ArchiveTest.java#L220-L285) for examples.

**Comment by gotson** [comment]
I tested your file, it works well. Please provide the code you are using to perform the extract.

**Comment by zhanghai** [comment]
The code is at https://github.com/zhanghai/MaterialFiles/blob/914692580391dcef06a3bfd45a22a19285cd0c0c/app/src/main/java/me/zhanghai/android/files/provider/archive/archiver/ArchiveReader.kt#L297 . Even if extraction have to be done sequentially for solid archives, maybe the library still shouldn't throw a `NullPointerException`?

**Comment by gotson** [comment]
Can you provide a minimal reproduction repo that shows the problem?

**Comment by zhanghai** [comment]
Hi @gotson,

Thank you for taking a look and explaining to me that the extraction only works when done sequantially. I'll look into doing that in my file manager,

Although fixing the NPE would be nice-to-have, and the code path for hitting the NPE is explained in the first comment, I only have limited time working on my open-source projects recently and can't provide an MRE for this. So if an MRE is required to fix the NPE, please feel free to close this issue.

**Comment by gotson** [comment]
I can't reproduce the npe on my side with your file and code. The code your point at is very low level, and it's not clear why a npe would be thrown there.
