### ISSUE TITLE
[BUG] Exception swallowed during initialization -- silently missing data we used to get in 7.4.1

### ISSUE THREAD

**Issue by tballison** [junrar/junrar#86]
**Describe the bug**
In 7.5.0, the parser is stopping earlier than it did in 7.4.1 without throwing an exception.  The exception is logged, but the client has no idea that there was a problem with the file.

**To Reproduce**
Iterate through the entries...
```
          Archive rar = new Archive(tis.getFile());

            if (rar.isEncrypted()) {
                throw new EncryptedDocumentException();
            }

            FileHeader header = rar.nextFileHeader();
            while (header != null && !Thread.currentThread().isInterrupted()) {
                //DO STUFF
                header = rar.nextFileHeader();
            }
```
**Expected behavior**
Please throw the exception or continue parsing the file as happened in 7.4.1.

**File**
The file is part of our large regression corpus tests over on Apache Tika.  We grabbed this file from Common Crawl.  It is possible that it is truncated.  My Ubuntu package utility does not like the file.  It may actually be corrupted.  We were able to get quite a bit more data out of it with 7.4.1.

https://corpora.tika.apache.org/base/docs/commoncrawl3/3X/3X4JRZZ4TQ2GK4QQDQEXMFCVLM3FM5I4 

**Environment (please complete the following information):**
 - OS: Ubuntu, but not relevant
 - Junrar version: 7.5.0

**Additional context**
Decompiler shows the issue in Archive#setChannel:
```
        try {
            this.readHeaders(length);
        } catch (UnsupportedRarV5Exception | CorruptHeaderException | BadRarArchiveException | UnsupportedRarEncryptedException var6) {
            logger.warn("exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented", var6);
            throw var6;
        } catch (Exception var7) {
            logger.warn("exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented", var7);
        }
```

The exception is:
```
WARN  [main] 19:50:32,239 com.github.junrar.Archive exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented
java.lang.ArrayIndexOutOfBoundsException: 55
	at com.github.junrar.io.Raw.readShortLittleEndian(Raw.java:104) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.rarfile.FileHeader.<init>(FileHeader.java:192) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.readHeaders(Archive.java:439) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.setChannel(Archive.java:198) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.setVolume(Archive.java:778) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.<init>(Archive.java:148) ~[junrar-7.5.0.jar:?]
	at com.github.junrar.Archive.<init>(Archive.java:161) ~[junrar-7.5.0.jar:?]
	at org.apache.tika.parser.pkg.RarParser.parse(RarParser.java:75) ~[classes/:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281) ~[classes/:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281) ~[classes/:?]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[classes/:?]
```

**Comment by gotson** [comment]
> We were able to get quite a bit more data out of it with 7.4.1.

Can you expand on that?

**Comment by gotson** [comment]
@andrebrait it seems linked to the changed done in #76 , if you have some time would you mind having a look ?

**Comment by THausherr** [comment]
I forgot to mention in the discussion in tika yesterday that 7zip shows the content
![grafik](https://user-images.githubusercontent.com/6665575/165430412-36f43ecb-18ab-4829-b251-5dc72ff0b4c6.png)

**Comment by gotson** [comment]
the official `unrar` cli as well as The Unarchiver on Mac can extract the archive without problem.

**Comment by andrebrait** [comment]
@gotson will do. Expect a PR by the end of the week, at most. Will try to get it fixed by EOD today.

**Comment by andrebrait** [comment]
@gotson, @THausherr, @tballison
Fixed it: #87

**Comment by gotson** [comment]
Thanks a lot @andrebrait for the reactivity. I will have a look tomorrow and if everything looks OK I'll merge and release.

**Comment by tballison** [comment]
Thank you!

**Comment by tballison** [comment]
If you ever need more files, we have some: https://corpora.tika.apache.org/datasette/file_profiles?sql=select+file_path%2C+length%2C+mime_string%0D%0Afrom+file_profiles+p%0D%0Ajoin+file_mimes+m+on+p.tika_mime_id+%3D+m.mime_id%0D%0Awhere+mime_id+in+%2898%2C+99%2C+152%2C+448%29%0D%0Aorder+by+length+asc%0D%0A

The ones around 1MB are likely to be truncated.
