### ISSUE TITLE
[BUG] "IllegalArgumentException: Pipe Size <= 0" with an empty file in the archive

### ISSUE THREAD

**Issue by AlexisJehan** [junrar/junrar#88]
**Describe the bug**
Reading an archive with an empty file is throwing an IllegalArgumentException.

**To Reproduce**
```java
try (final var archive = new Archive(Path.of("file.rar").toFile())) {
	while (true) {
		final var fileHeader = archive.nextFileHeader();
		if (null == fileHeader) {
			break;
		}
		final var outputStream = new ByteArrayOutputStream();
		//archive.extractFile(fileHeader, outputStream); // OK
		archive.getInputStream(fileHeader).transferTo(outputStream); // IllegalArgumentException: Pipe Size <= 0
		System.out.println(outputStream);
	}
}
```

**Expected behavior**
Should return an empty InputStream instead of throwing an IllegalArgumentException.

**File**
[file.rar.zip](https://github.com/junrar/junrar/files/8619620/file.rar.zip)
(need to extract the ZIP file to get the RAR inside)

**Environment (please complete the following information):**
 - OS: Windows
 - Junrar version: 7.5.1 (latest)

**Additional context**
None

**Comment by tballison** [comment]
We found this too over on Apache Tika.  We added a size check on the header and if == 0, we skipped the stream.

**Comment by gotson** [comment]
Probably coming from here https://github.com/junrar/junrar/blob/36c56d766793bbc21a9d5752dbcf67e42d75a4d2/src/main/java/com/github/junrar/Archive.java#L647 as the buffer size would be zero.

I suppose we can add a check for the header size and return an empty stream instead.

**Comment by gotson** [comment]
@andrebrait seems like it's been introduced by one of your change. Do you want to take care of this one?

**Comment by andrebrait** [comment]
@gotson sure thing

**Comment by andrebrait** [comment]
@gotson done #90
