### ISSUE TITLE
Hrlp me 

### ISSUE THREAD

**Issue by Arashvscode** [junrar/junrar#94]
Hello my used in code 

```java
try{
	Junrar.extract("/storage/emulated/0/Download/rarlng_android.rar", "/storage/emulated/0/Download/");
}catch(Exception e){
	Toast.makeText(getApplicationContext(), e.toString(), Toast.LENGTH_SHORT).show();

}
```

End app me Error not The file is not extracted

![Screenshot_20220623-225901_rar](https://user-images.githubusercontent.com/101287880/175369770-dba8ab2e-059b-42f1-a63f-5159a2c5c035.jpg)

If you can help me and send me a Java code, I can extract it in the file path. Thank you. I am waiting for your reply.

**Comment by gotson** [comment]
Junrar doesn't support RAR 5 files, see #23.
